#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  3 21:31:48 2019

@author: fangyucheng
Email: 664947387@qq.com
"""

str1 = '我爱我家'
str2 = 'I like my home'
str3 = 'Ilikemyhome'


print(str1.isalpha())
print(str2.isalpha())
print(str3.isalpha())